### PR TITLE
Disable performance measurements and enable optimizations on Windows

### PR DESCRIPTION
**Pull request by cgohlke**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

https://stackoverflow.com/questions/77680445/how-to-disable-python-imagecodecs-perf-report

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Please bump three build number too

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
its a pretty old package, so its likely that the compiler updates will break something, but at least the CIs are running.

**Comment by cgohlke** [comment]
For the macOS build failures, try this patch:
```patch
diff --git a/image/decode/segdec.c b/image/decode/segdec.c
index fb83f2b..1eb9ae4 100644
--- a/image/decode/segdec.c
+++ b/image/decode/segdec.c
@@ -52,6 +52,9 @@ static Int DecodeSignificantAbsLevel (struct CAdaptiveHuffman *pAHexpt, BitIOInf
 //================================================================
 // Memory access functions
 //================================================================
+
+U32 _byteswap_ulong(U32 bits);
+
 static U32 _FORCEINLINE _load4(void* pv)
 {
 #ifdef _BIG__ENDIAN_
diff --git a/jxrgluelib/JXRGlueJxr.c b/jxrgluelib/JXRGlueJxr.c
index 0fde9bb..e6c54e4 100644
--- a/jxrgluelib/JXRGlueJxr.c
+++ b/jxrgluelib/JXRGlueJxr.c
@@ -28,7 +28,7 @@
 //*@@@---@@@@******************************************************************
 #include <limits.h>
 #include <JXRGlue.h>
-
+#include <wchar.h>
 
 static const char szHDPhotoFormat[] = "<dc:format>image/vnd.ms-photo</dc:format>";
 const U32 IFDEntryTypeSizes[] = { 0, 1, 1, 2, 4, 8, 1, 1, 2, 4, 8, 4, 8 };
```

**Comment by hmaarrfk** [comment]
its your PR ;)

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
Sigh. Somebody should call unix2dos

**Pull request merged**
